compressionLevel: mixed

enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.com/"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.0.2.cjs
