nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-berry.cjs

supportedArchitectures:
  os: [linux, darwin]
  cpu: [x64, arm64]

npmRegistryServer: "https://registry.npmjs.com/"

nmHoistingLimits: "dependencies"
