nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

npmRegistryServer: "https://propel-493852367691.d.codeartifact.us-east-2.amazonaws.com/npm/propel/"
