name: 'propel-code-artifact'
description: 'logs into propels code artifact and sets-up yarn and npm auth'
inputs:
  aws_access_key_id:
    required: true
    description: 'access key id'
  aws_secret_access_key:
    required: true
    description: 'access secret key'
  aws_default_region:
    required: true
    description: 'region'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        export AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}
        export AWS_DEFAULT_REGION=${{ inputs.aws_default_region }}
        aws codeartifact login --domain propel --repository propel --tool npm

        # NOTE(mroberts): Don't do this, since we have lockfiles...
        # sed -i -e 's/^registry=/@propeldata:registry=/' ~/.npmrc

        npm config set ${{$CODEARTIFACT_REPO}}:_authToken=${{ $CODEARTIFACT_AUTH_TOKEN }}

        # NOTE(mroberts): This is for Yarn v2 and above.
        export AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}
        export AWS_DEFAULT_REGION=${{ inputs.aws_default_region }}
        export CODEARTIFACT_REPO=$(aws codeartifact get-repository-endpoint --domain propel --repository propel --format npm --output text)
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain propel --query authorizationToken --output text)
        yarn config set -H npmRegistryServer "$CODEARTIFACT_REPO"
        yarn config set -H "npmRegistries[\"$CODEARTIFACT_REPO\"].npmAuthToken" $CODEARTIFACT_AUTH_TOKEN
