// @ts-nocheck
import '@propeldata/wc-time-series'

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <time-series accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3RpbWUiOjE2Njg2OTE2NTIsImNsaWVudF9pZCI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwiZXhwIjoxNjY4Njk1MjUyLCJpYXQiOjE2Njg2OTE2NTIsImlzcyI6Imh0dHBzOi8vYXV0aC51cy1lYXN0LTIuZGV2LnByb3BlbGRhdGEuY29tIiwianRpIjoiODk1YjNkN2ItMjFjYi00MmQ3LWI1MTYtYTAwZDdhMTkzNjA4IiwicHJvcGVsL3RlbmFudCI6IkVOVjAxRlgzNjA2UjJLUUZRWVhYMzRBOTZRNlpSIiwic2NvcGUiOiJtZXRyaWM6cXVlcnkgcHJvcGVsL21ldHJpYzpxdWVyeSIsInN1YiI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwidmVyc2lvbiI6MX0.MutIQk55QAMh112i4G1EY3weZkMxJaMUzti0yg3qnwA"></time-series>  
`
