import '@propeldata/wc-time-series'
import '@propeldata/wc-counter'

document.querySelector<HTMLDivElement>('#time-series')!.innerHTML = `
  <time-series metric="queryCount" accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3RpbWUiOjE2NjkyMzU0MTEsImNsaWVudF9pZCI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwiZXhwIjoxNjY5MjM5MDExLCJpYXQiOjE2NjkyMzU0MTEsImlzcyI6Imh0dHBzOi8vYXV0aC51cy1lYXN0LTIuZGV2LnByb3BlbGRhdGEuY29tIiwianRpIjoiMzVmYzlhY2EtMzljNS00NzdlLTk1N2QtMjExZGI1ZDQyNGEzIiwicHJvcGVsL3RlbmFudCI6IkVOVjAxRzdUMlhLQTk5QzEwVFZWUlc0NlBONzhQIiwic2NvcGUiOiJtZXRyaWM6cXVlcnkgcHJvcGVsL21ldHJpYzpxdWVyeSIsInN1YiI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwidmVyc2lvbiI6MX0.KI_qGteATy07BANryQ6muQkGYjb-qs_YleyoP9LYEVs"></time-series>  
`

document.querySelector<HTMLDivElement>('#counter')!.innerHTML = `
  <counter-web metric="queryCount" accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3RpbWUiOjE2NjkyMzU0MTEsImNsaWVudF9pZCI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwiZXhwIjoxNjY5MjM5MDExLCJpYXQiOjE2NjkyMzU0MTEsImlzcyI6Imh0dHBzOi8vYXV0aC51cy1lYXN0LTIuZGV2LnByb3BlbGRhdGEuY29tIiwianRpIjoiMzVmYzlhY2EtMzljNS00NzdlLTk1N2QtMjExZGI1ZDQyNGEzIiwicHJvcGVsL3RlbmFudCI6IkVOVjAxRzdUMlhLQTk5QzEwVFZWUlc0NlBONzhQIiwic2NvcGUiOiJtZXRyaWM6cXVlcnkgcHJvcGVsL21ldHJpYzpxdWVyeSIsInN1YiI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwidmVyc2lvbiI6MX0.KI_qGteATy07BANryQ6muQkGYjb-qs_YleyoP9LYEVs"></counter-web>  
`
