import '@propeldata/wc-time-series'
import '@propeldata/wc-counter'

document.querySelector<HTMLDivElement>('#time-series')!.innerHTML = `
  <time-series metric="queryCount" accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3RpbWUiOjE2NjkzMTA0MjIsImNsaWVudF9pZCI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwiZXhwIjoxNjY5MzE0MDIyLCJpYXQiOjE2NjkzMTA0MjIsImlzcyI6Imh0dHBzOi8vYXV0aC51cy1lYXN0LTIuZGV2LnByb3BlbGRhdGEuY29tIiwianRpIjoiNTVhMjU2NTktZGQ3YS00ZmYxLTg3NzctZTFmOTU0YzVlYzJmIiwicHJvcGVsL3RlbmFudCI6IkVOVjAxRlgzNjA2UjJLUUZRWVhYMzRBOTZRNlpSIiwic2NvcGUiOiJtZXRyaWM6cXVlcnkgcHJvcGVsL21ldHJpYzpxdWVyeSIsInN1YiI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwidmVyc2lvbiI6MX0.atJiIdrPZaAeWk1Fwr3u58bwEdt4KVNvNGyZhla3cJ0"></time-series>  
`

document.querySelector<HTMLDivElement>('#counter')!.innerHTML = `
  <wc-counter metric="queryCount" accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3RpbWUiOjE2NjkzMTA0MjIsImNsaWVudF9pZCI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwiZXhwIjoxNjY5MzE0MDIyLCJpYXQiOjE2NjkzMTA0MjIsImlzcyI6Imh0dHBzOi8vYXV0aC51cy1lYXN0LTIuZGV2LnByb3BlbGRhdGEuY29tIiwianRpIjoiNTVhMjU2NTktZGQ3YS00ZmYxLTg3NzctZTFmOTU0YzVlYzJmIiwicHJvcGVsL3RlbmFudCI6IkVOVjAxRlgzNjA2UjJLUUZRWVhYMzRBOTZRNlpSIiwic2NvcGUiOiJtZXRyaWM6cXVlcnkgcHJvcGVsL21ldHJpYzpxdWVyeSIsInN1YiI6Ijd0dDVpbDE5MmhsYmthZGYwY2NnNGk3c3Q2IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwidmVyc2lvbiI6MX0.atJiIdrPZaAeWk1Fwr3u58bwEdt4KVNvNGyZhla3cJ0"></wc-counter>  
`
