name: 'prepare'
description: 'compile the project with all the appropriate caches'
inputs:
  cache_key_suffix:
    description: 'Suffix to use for the cache key'
    required: false
    default: ''
  cache_fresh_start:
    description:
      "Restarts the cache, this needs to be done sot that turborepo's cache doesn't grow unbounded
      https://github.com/vercel/turborepo/issues/863"
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Setup Node'
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
    - name: 'Cache node_modules'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}${{ inputs.cache_key_suffix }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}${{ inputs.cache_key_suffix }}
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-yarn-
    - name: 'Prune cache'
      shell: bash
      if: ${{ inputs.cache_fresh_start == 'true' }}
      run: rm -rf node_modules/.cache
    - name: 'Install the project'
      shell: bash
      run: yarn install
    - name: 'Compile the project'
      shell: bash
      run: yarn prepare
