#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$" && \
   ! head -1 "$1" | grep -qE "^Version Packages"; then
    echo "🚫 Aborting commit. Your commit message is invalid. Please, follow the conventional commits spec (https://www.conventionalcommits.org/en/v1.0.0/) or use 'Version Packages' for package updates." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "🚫 Aborting commit. Your commit message is too long." >&2
    exit 1
fi