name: check-pull-request
on:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          repository: propeldata/actions
          token: ${{ secrets.PROPELDATA_CI_TOKEN }}
          path: actions
      - uses: ./actions/propel-code-artifact
        with:
          aws_access_key_id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws_default_region: ${{ secrets.BUILD_AWS_DEFAULT_REGION }}
      - uses: ./.github/actions/prepare
        with:
          cache_key_suffix: '-unit-test'
      - run: yarn test

  # lint:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: propeldata/actions
  #         token: ${{ secrets.PROPELDATA_CI_TOKEN }}
  #         path: actions
  #     - uses: ./actions/propel-code-artifact
  #       with:
  #         aws_access_key_id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
  #         aws_default_region: ${{ secrets.BUILD_AWS_DEFAULT_REGION }}
  #     - uses: ./.github/actions/prepare
  #       with:
  #         cache_key_suffix: '-lint'
  #     - run: yarn lint
